import { Navbar } from '@/components';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = (
  {
    children,
  }: {
      children: React.ReactNode
    },
) => (
  <html lang='en'>
    <body className='bg-secondary text-white'>
      <Navbar />
      <div className='px-40 py-6'>
        {children}
      </div>
    </body>
  </html>
);

export default RootLayout;
